/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TechnicalRouteImport } from './routes/technical'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/coaches': typeof CoachesRoute
  '/merchandise': typeof MerchandiseRoute
  '/personnel': typeof PersonnelRoute
  '/players': typeof PlayersRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/teams': typeof TeamsRoute
  '/technical': typeof TechnicalRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/coaches': typeof CoachesRoute
  '/merchandise': typeof MerchandiseRoute
  '/personnel': typeof PersonnelRoute
  '/players': typeof PlayersRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/teams': typeof TeamsRoute
  '/technical': typeof TechnicalRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/coaches': typeof CoachesRoute
  '/merchandise': typeof MerchandiseRoute
  '/personnel': typeof PersonnelRoute
  '/players': typeof PlayersRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/teams': typeof TeamsRoute
  '/technical': typeof TechnicalRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/admin'
    | '/branches'
    | '/calendar'
    | '/coach'
    | '/coaches'
    | '/merchandise'
    | '/personnel'
    | '/players'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/teams'
    | '/technical'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/admin'
    | '/branches'
    | '/calendar'
    | '/coach'
    | '/coaches'
    | '/merchandise'
    | '/personnel'
    | '/players'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/teams'
    | '/technical'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/admin'
    | '/branches'
    | '/calendar'
    | '/coach'
    | '/coaches'
    | '/merchandise'
    | '/personnel'
    | '/players'
    | '/sessions'
    | '/settings'
    | '/setup'
    | '/teams'
    | '/technical'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AdminRoute: typeof AdminRoute
  BranchesRoute: typeof BranchesRoute
  CalendarRoute: typeof CalendarRoute
  CoachRoute: typeof CoachRoute
  CoachesRoute: typeof CoachesRoute
  MerchandiseRoute: typeof MerchandiseRoute
  PersonnelRoute: typeof PersonnelRoute
  PlayersRoute: typeof PlayersRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TeamsRoute: typeof TeamsRoute
  TechnicalRoute: typeof TechnicalRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AdminRoute: AdminRoute,
  BranchesRoute: BranchesRoute,
  CalendarRoute: CalendarRoute,
  CoachRoute: CoachRoute,
  CoachesRoute: CoachesRoute,
  MerchandiseRoute: MerchandiseRoute,
  PersonnelRoute: PersonnelRoute,
  PlayersRoute: PlayersRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TeamsRoute: TeamsRoute,
  TechnicalRoute: TechnicalRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
